### ISSUE TITLE
Reference (still) not found

### ISSUE THREAD

**Issue by pateketrueke** [json-schema-faker/refaker#1]
Given this schema: https://gist.github.com/raitucarp/2ac86c96226371bc80d7

I see that refaker cannot resolve due some redirects and fails on proper caching them, etc.

Related issue: https://github.com/pateketrueke/json-schema-faker/issues/28

**Comment by shannoncurnew** [comment]
Given

`"$schema": "http://json-schema.org/draft-04/schema#",`
...
`"effective_date_utc": {
    "$ref": "date_time_v_1.0.0.json#/definitions/DateTime"
},`

I get a `Error: Reference not found: http://json-schema.org/draft-04/date_time_v_1.0.0.json#/definitions/DateTime`

Is this related? I believe the schema format is correct for referencing external files in the same directory.
